In [1]:
import pandas as pd
import numpy as np

In [2]:
#Question1
A = [1,2,3,4,5,6]
B=[13,21,34]


In [3]:
print(A.extend(B))

None


In [4]:
print(A.append(B))

None


In [5]:
#answer: None of the above

In [6]:
#Question2

In [7]:
print(eyes(3))

NameError: name 'eyes' is not defined

In [8]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(np.array([1,0,0], [0,1,0],[0,0,1]))

ValueError: only 2 non-keyword arguments accepted

In [13]:
print(np.array[(1,0,0),(0,1,0),(0,0,1)])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [14]:
#answer: np.identity(3) 

In [15]:
data = pd.read_csv('fuel_ferc1.csv')

In [16]:
data.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [17]:
data.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [23]:
#Question3
data.groupby('fuel_type_code_pudl')[['fuel_cost_per_unit_burned']].mean().sort_values(
    ascending=True, by='fuel_cost_per_unit_burned')
#answer: gas

fuel_cost_per_unit_burned
fuel_type_code_pudl                           
gas                                  13.659397
other                                18.253856
waste                                19.518122
coal                                 67.421830
oil                                 168.877086
nuclear                            4955.157002

In [25]:
#Question4
print(data['fuel_mmbtu_per_unit'].std()) #Standard deviation
print(data['fuel_mmbtu_per_unit'].quantile(0.75)) #75 percentile
#answer: 10.60 and 17.01

10.600220307806886
17.006


In [29]:
#Question5
print(data['fuel_qty_burned'].skew())
print(data['fuel_qty_burned'].kurtosis())
#answer: 15.85 and 651.37

15.851495469109503
651.3694501337732


In [40]:
#Question6
print(data.isnull().sum())
percent= data['fuel_unit'].isnull().sum() / len(data['fuel_unit']) * 100
print(percent)
#answer: Feature: fuel_unit, Total: 180, Percent: 0.609694136774718

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
0.609694136774718


In [41]:
#Question7
print(data['fuel_unit'].dtype)
#answer: categorical and mode imputation

object


In [44]:
#WQuestion8
data.corr()["fuel_cost_per_unit_burned"].sort_values(ascending=True)[1:3]
#answer: fuel_qty_burned and fuel_mmbtu_per_unit

fuel_qty_burned       -0.018535
fuel_mmbtu_per_unit   -0.010034
Name: fuel_cost_per_unit_burned, dtype: float64

In [67]:
#Question 9
a = data.groupby(
    ['report_year', 'fuel_type_code_pudl'])[['fuel_cost_per_unit_burned']].sum().reset_index()

fcpub_coal_1994 = a[(a['report_year'] == 1994) &  (a['fuel_type_code_pudl'] == 'coal')
      ].fuel_cost_per_unit_burned[0]

fcpub_coal_1998 = a[(a['report_year'] == 1998) &  (a['fuel_type_code_pudl'] == 'coal')
      ].fuel_cost_per_unit_burned[24]

#fcupb_coal_1994 = fuel_cost_per_unit_burned_coal_1994
#fcupb_coal_1998 = fuel_cost_per_unit_burned_coal_1994

((fcpub_coal_1998 - fcpub_coal_1994) / fcpub_coal_1994) * 100

#answer: -21%

-20.56765451826049

In [68]:
#Question10
data.groupby('report_year')[['fuel_cost_per_unit_delivered']].mean().sort_values(
    ascending=False, by='fuel_cost_per_unit_delivered')

#answer: 1997

fuel_cost_per_unit_delivered
report_year                              
1997                         11140.197239
1996                          9196.705948
2000                           985.362877
2009                           652.694163
2018                           499.269966
2015                           326.535511
1998                           287.154420
2014                           192.737183
2013                           172.307591
2004                           139.524275
2016                           103.901761
2010                            91.862105
1994                            63.636060
2012                            60.994502
2001                            60.050396
2011                            59.774667
2008                            58.588197
2003                            55.663493
2002                            47.594361
2017                            46.196861
2007                            43.325023
2005                            41.438184
2006                            38.657484
1995                            32.735269
1999                            25.551627